using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace OsTicket.API
{
    /// <summary>
    /// The OSTicket API Wrapper 
    /// </summary>
    public class APIProxy 
    {

        public event EventHandler<RestResponseEventArgs> RequestCompleted;

        /// <summary>
        /// Construct an instance of the API Proxy class
        /// </summary>
        /// <param name="osTicketUrl">The base URL of the OsTicket instance (minus the /api part)</param>
        /// <param name="apiKey">The API Key that was generated by the OsTicket instance.</param>
        public APIProxy(string osTicketUrl, string apiKey)
        {
            this.OsTicketUrl = osTicketUrl;
            this.ApiKey = apiKey;
        }

        /// <summary>
        /// Retrieve a list of priorities from the OsTicket instance
        /// </summary>
        /// <returns>A value to string dictionary of all publicly available priorities in the OsTicket instance</returns>
        /// <remarks>Requires that the Priority.php API extension method be installed on the OsTicket instance</remarks>
        public Dictionary<int, string> GetPriorities()
        {
            RestClient client = new RestClient(OsTicketUrl);

            IRestRequest request = new RestRequest("/api/priority.php", Method.POST);
            request.AddHeader("X-API-KEY", ApiKey);

            IRestResponse response = client.Execute(request);

            JObject root = JObject.Parse(response.Content);
            JsonSerializer serializer = new JsonSerializer();
            return serializer.Deserialize<Dictionary<int, string>>(root.CreateReader());
        }

        /// <summary>
        /// Retrieve a list of help topics from the OsTicket instance
        /// </summary>
        /// <returns>A value to string dictionary of all publicly available help topics in the OsTicket instance</returns>
        /// <remarks>Requires that the Topic.php API extension method be installed on the OsTicket instance</remarks>
        public Dictionary<int, string> GetTopics()
        {
            RestClient client = new RestClient(OsTicketUrl);

            IRestRequest request = new RestRequest("/api/topic.php", Method.POST);
            request.AddHeader("X-API-KEY", ApiKey);

            IRestResponse response = client.Execute(request);

            JObject root = JObject.Parse(response.Content);
            JsonSerializer serializer = new JsonSerializer();
            return serializer.Deserialize<Dictionary<int, string>>(root.CreateReader());
        }

        /// <summary>
        /// Retrieve a list of of tickets from the OsTicket instance
        /// </summary>
        /// <returns>a list of all tickets associated with the user or the orderid</returns>
        /// <remarks>Requires that the forumtickets.php API extension method be installed on the OsTicket instance</remarks>
        public RestResponseEventArgs GetTickets(Dictionary<string, string> parameters = null)
        {
            RestClient client = new RestClient(OsTicketUrl);

            IRestRequest request = new RestRequest("/api/forumtickets.php", Method.POST);
            request.AddHeader("X-API-KEY", ApiKey);
            if (parameters != null)
            {
                foreach (var item in parameters)
                {
                    request.AddParameter(item.Key, item.Value);
                }
            }

            IRestResponse response = client.Execute(request);
            return new RestResponseEventArgs(response);
        }

        public RestRequestAsyncHandle GetTicketsAsync(Dictionary<string,string> parameters = null)
        {
            RestClient client = new RestClient(OsTicketUrl);

            IRestRequest request = new RestRequest("/api/forumtickets.php", Method.POST);
            request.AddHeader("X-API-KEY", ApiKey);
            if (parameters != null)
            {
                foreach (var item in parameters)
                {
                    request.AddParameter(item.Key, item.Value);
                }
            }
                
            Action<IRestResponse> action = (restresponse) => { RequestCompleted?.Invoke(this, new RestResponseEventArgs(restresponse)); };

            return client.ExecuteAsync(request, action);
        }


        /// <summary>
        /// Submits a ticket to the OsTicket instance.
        /// </summary>
        /// <param name="ticket">The Ticket to Submit</param>
        /// <returns>The generated ticket id.</returns>
        public RestResponseEventArgs SubmitTicket(Ticket ticket)
        {
            RestClient client = new RestClient(OsTicketUrl);

            IRestRequest request = new RestRequest("/api/tickets.json", Method.POST);
            request.JsonSerializer = new RestSharp.Serializers.NetwonsoftJsonSerializer();
            request.AddHeader("X-API-KEY", ApiKey);
            request.RequestFormat = DataFormat.Json;

            TicketDTO ticketDTO = TicketDTO.CreateFromTicket(ticket);
            JObject jo = JObject.FromObject(ticketDTO);
            foreach (KeyValuePair<string, object> pair in ticket.ExtraFields)
            {
                jo.Add(pair.Key, JToken.FromObject(pair.Value));
            }

            request.AddBody(jo);
           
            IRestResponse response = client.Execute(request);
            return new RestResponseEventArgs(response);
            
        }

        /// <summary>
        /// Submits a ticket to the OsTicket instance asynchronously.
        /// </summary>
        /// <param name="ticket">The Ticket to Submit</param>
        /// <returns>The generated ticket id.</returns>
        public RestRequestAsyncHandle SubmitTicketAsync(Ticket ticket)
        {
            RestClient client = new RestClient(OsTicketUrl);

            IRestRequest request = new RestRequest("/api/tickets.json", Method.POST);
            request.JsonSerializer = new RestSharp.Serializers.NetwonsoftJsonSerializer();
            request.AddHeader("X-API-KEY", ApiKey);
            request.RequestFormat = DataFormat.Json;

            TicketDTO ticketDTO = TicketDTO.CreateFromTicket(ticket);
            JObject jo = JObject.FromObject(ticketDTO);
            foreach (KeyValuePair<string, object> pair in ticket.ExtraFields)
            {
                jo.Add(pair.Key, JToken.FromObject(pair.Value));
            }

            request.AddBody(jo);

            Action<IRestResponse> action = (restresponse) => { RequestCompleted?.Invoke(this, new RestResponseEventArgs(restresponse)); };

            return client.ExecuteAsync(request,action);

        }

        /// <summary>
        /// The Root URL of the OsTicket instance (http://support.blah.com, not http://support.blah.com/api)
        /// </summary>
        public string OsTicketUrl
        {
            get;
            private set;
        }

        /// <summary>
        /// The API Key generated by OsTicket
        /// </summary>
        public string ApiKey
        {
            get;
            private set;
        }
    }

    public sealed class RestResponseEventArgs : EventArgs
    {
        public IRestResponse RestResponse { get; } = null;
        public List<ListTicket> Tickets { get; } = null;
        public int TicketNumber { get; } = -1;
        public bool HasError { get; } = false;
        public string ErrorMessage { get; }

        public RestResponseEventArgs()
        {

        }
        public RestResponseEventArgs(IRestResponse value)
        {
            RestResponse = value;
            switch (RestResponse.StatusCode)
            {
                case HttpStatusCode.OK:
                    var tk = JsonConvert.DeserializeObject<List<ListTicket>>(RestResponse.Content);
                    Tickets = tk;
                    break;
                case HttpStatusCode.Created:
                    TicketNumber = int.Parse(RestResponse.Content);
                    break;
                default:
                    HasError = true;
                    ErrorMessage = $"{RestResponse.StatusCode} : {RestResponse.StatusDescription}";
                    break;
            }
           
        }
    }
}
